### ISSUE TITLE
Can't install using yarn because of dooboolab-welcome

### ISSUE THREAD

**Issue by trajano** [hyochan/react-native-masonry-list#24]
```
yarn install v1.22.17
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find package "dooboolab-welcome" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

npm install is fine

**Comment by hyochan** [comment]
@trajano Hello thanks for the issue.

Could you kindly go over https://registry.npmjs.org?](https://github.com/npm/cli/issues/1816 and see if this helps?

**Comment by trajano** [comment]
No luck, still getting the error.

**Comment by trajano** [comment]
Found the reason https://stackoverflow.com/questions/61407791/yarn-not-working-with-nexus-3-npm-proxy-repository/62828391#62828391

needed `always-auth=true` to make it work on Yarn.
