### ISSUE TITLE
Ability to use onScroll with the List

### ISSUE THREAD

**Issue by kayode0x** [hyochan/react-native-masonry-list#26]
I need to use `onScoll` to control my header, it's available to the native FlatList but it's not here. Can you fix this, please? thanks.

ps I get this error:
```
onScroll: (event: any) => void; }' is not assignable to type 'IntrinsicAttributes & Props<unknown>'.
  Property 'onScroll' does not exist on type 'IntrinsicAttributes & Props<unknown>'.
```

**Comment by jzxchiang1** [comment]
Not sure why this was explicitly disabled.

**Comment by kayode0x** [comment]
@jzxchiang1 were you able to fix this?

**Comment by kayode0x** [comment]
Were you able to use `onScroll` after patching the package? 😮

**Comment by jzxchiang1** [comment]
Yeah, so I wanted to use an Animated.event inside the onScroll, so I manually changed the library code to use that (and made the ScrollView an Animated.ScrollView).

**Comment by kayode0x** [comment]
Awesome, do you mind sharing your code? thanks

**Comment by kayode0x** [comment]
hey @jzxchiang1, can you share your source code or walkthrough on how to get this? thanks again

**Comment by danielprrazevedo** [comment]
@jzxchiang1 I'm a little late, but if you're still having problems, check [this](https://github.com/hyochan/react-native-masonry-list/issues/53#issuecomment-1364367961) out and see if it can help you.
