### ISSUE TITLE
Is there a way to disable "pull to refresh"?

### ISSUE THREAD

**Issue by GollyJer** [hyochan/react-native-masonry-list#28]
I feel like pull-to-refresh should be easy to disable but I'm missing how.
Possible?

Thanks.

**Comment by tareksmoubarak** [comment]
Hello, Just don't set:
`refreshing` and  `onRefresh` 
props

**Comment by GollyJer** [comment]
Hi @tareksmoubarak. Thanks for the response.
I'm not setting those props but it still shows the pull-to-refresh indicator.
![image](https://user-images.githubusercontent.com/689204/155627671-cea09c47-3920-4d84-a025-e209db697802.png)

Strange.

**Comment by GollyJer** [comment]
OK, just had a look at the code and the refreshing state is hard coded.
[  const [isRefreshing, setIsRefreshing] = useState<boolean>(false);](https://github.com/hyochan/react-native-masonry-list/blob/058642f08d62e9f710edfc97b6ef89462c391325/index.tsx#L48)

Looks like this is intended behavior.
Closing this issue.

**Comment by YahyaBagia** [comment]
@hyochan any way to prevent Pull to refresh ?
