### ISSUE TITLE
Add keyboardShouldPersistTaps="handled"

### ISSUE THREAD

**Issue by jzxchiang1** [hyochan/react-native-masonry-list#29]
**Is your feature request related to a problem? Please describe.**
Without this, Android will require two taps if the MasonryList contains Pressables.

**Describe the solution you'd like**
Self-explanatory.

**Describe alternatives you've considered**
Self-explanatory.

**Additional context**
https://github.com/facebook/react-native/issues/4087

**Comment by hyochan** [comment]
@jzxchiang1 Thanks for the issue. Do you think this should be added to default component?

**Comment by lucianomlima** [comment]
@hyochan this can be added by default without issues. I can open a PR for this.
Can you add hacktoberfest label please? 🙏

**Comment by hyochan** [comment]
> @hyochan this can be added by default without issues. I can open a PR for this. Can you add hacktoberfest label please? 🙏

@lucianomlima I've just done it!!

Also, I hope you like our github stats here too!
![lucianomlima  GitHub Stats](https://server.dooboo.io/github-stats-advanced/lucianomlima)

This can be found in [dooboo.io](https://dooboo.io). [This is just FYI](https://medium.com/dooboolab/a-new-fancy-way-to-visualize-your-github-stats-418b5d59498).
