### ISSUE TITLE
Cannot Disable Pull To Refresh

### ISSUE THREAD

**Issue by RianTritiYanuar-ICube** [hyochan/react-native-masonry-list#40]
I have `TouchableOpacity` as the parent of item that render on `renderItem`. And when i do longpress and swipe to down it is doing Pull To Refresh. Is there any proper way to disable Pull To Refresh? 

The docs said this package extended `ScrollView` props, but when i set `bounces` to `false` it's still able to Pull To Refresh.

**Comment by hyochan** [comment]
Released #39

**Comment by FengFuLiu** [comment]
I have the same problem ,When PR can be merged?

**Comment by hyochan** [comment]
Closes #39
