### ISSUE TITLE
Typescript Error: Module '"react-native"' has no exported member 'Omit'

### ISSUE THREAD

**Issue by zerobertelprivat** [hyochan/react-native-masonry-list#55]
After updating to react-native 71.8 i am getting this bug
in @react-native-seoul/masonry-list/lib/index.d.ts
in line ->
import type { Omit, RefreshControlProps, ScrollViewProps, StyleProp, ViewStyle } from 'react-native';

There is no "Omit" in react-native, if i remove the Omit import, dependent issues disappear, too

Thanks for your time

**Comment by hyochan** [comment]
@zerobertelprivat Thanks for this. Fixed in `1.4.2`

**Comment by zerobertelprivat** [comment]
Thank you for your fast reply! :)
