### ISSUE TITLE
Wondering how to dynamic define the height of the item? The screenshot looks fancy, is there code share?

### ISSUE THREAD

**Issue by dongdyang** [hyochan/react-native-masonry-list#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hyochan** [comment]
Yes you can see the [MaonsryList Example](https://github.com/hyochan/react-native-masonry-list/tree/master/RNMasonryExample). There is also [Youtube](https://www.youtube.com/watch?v=QxSKAcKKW_Q&t=44s)

**Comment by soly2014** [comment]
Hello @hyochan , thank u very much for ur awesome lib
i wonder if i have dynamic height with the real image dimension instead of random height

**Comment by hyochan** [comment]
@soly2014 I don't think this is the role of the library itself. However, I already tried this implementation on my side and I'll share this shortly.

1. Create `getOriginalImageSize` function.

```ts
export const getOriginalImageSize = async (
  imageUri: string,
): Promise<ImageSize> =>
  new Promise<ImageSize>((resolve, reject) =>
    Image.getSize(
      imageUri,
      (width: number, height: number) =>
        resolve({
          width,
          height,
        }),
      reject,
    ),
 );
```

2. Get image `aspectRatio` during rendering.
```tsx
  const [imgAspectRatio, setImgAspectRatio] = useState<number>(0);

  const getImageRatio = useCallback(async (): Promise<void> => {
    const imageSize = await getOriginalImageSize(imageURL);

    if (imageSize) setImgAspectRatio(imageSize.height / imageSize.width);
  }, [imageURL]);

  useEffect(() => {
    getImageRatio();
  }, [getImageRatio]);
```

3. Put `aspectRatio` to `Image`.
```tsx
<Image
  progressiveRenderingEnabled
  source={{uri: itemImageURL}}
  resizeMode="cover"
  style={{
    alignSelf: 'stretch',
    width: '100%',
    aspectRatio: imgAspectRatio,
}}/>
```

**Comment by soly2014** [comment]
@hyochan nice man how we can handle performance in case of large datasets ??
i mean virtualization
